# WARNING:
# This file is automatically generated by makegen.
# It is not intended for manual editing.

check_defined = \
$(strip $(foreach 1,$1, \
    $(call __check_defined,$1,$(strip $(value 2)))))
__check_defined = \
$(if $(value $1),, \
    $(error Mandatory argument $1$(if $2, ($2))$(if $(value @), \
            not provided. Required by target `$@`)))

log_prefix := \x1b[34m[\u001b[0m\x1b[31m*\x1b[34m\x1b[34m]\u001b[0m
command_prefix := \x1b[34m[\u001b[0m\x1b[31m\#\x1b[34m\x1b[34m]\u001b[0m


build:
	@:$(call check_defined, TYPE, "type to compile: release/debug")

	@echo -e "${log_prefix} "Running tests...""
	@echo -e "${command_prefix} "cargo test""
	@cargo test
	@echo -e "${log_prefix} "Compiling binary...""
	@echo -e "${command_prefix} "cargo build --target x86_64-pc-windows-gnu --$(TYPE) && mv target/release/config.exe .""
	@cargo build --target x86_64-pc-windows-gnu --$(TYPE) && mv target/release/config.exe .
